### ISSUE TITLE
Add Documentation for first good first issues and hacktoberfest

### ISSUE THREAD

**Issue by MostDeadDeveloper** [MostDeadDeveloper/BatiBot-The-Discord-Bot#23]
_Pasted:_ 
As of now I would like to dedicate a section of the READMe.md , so that it could give a brief description on how to submit your first PR, any possible tips to follow, and handful url links that any beginners could use. 

I think as long as you can give a brief  step by step guide on how to submit your first PR or to contribute in open-source projects, and handy URL Links as references, that will be perfect.

Don't hesitate to ask for any more questions, thank you for your help!

Edit: I will be modifying the other issues as well, just finding the time to do so.

**Comment by pratiksasmal** [comment]
Can you give a description as to what exactly you want?

**Comment by MostDeadDeveloper** [comment]
Ahh hi pratiksasmal! 

As of now I would like to dedicate a section of the READMe.md , so that it could give a brief description on how to submit your first PR, any possible tips to follow, and handful url links that any beginners could use. 

I think as long as you can give a brief  step by step guide on how to submit your first PR or to contribute in open-source projects, and handy URL Links as references, that will be perfect.

Don't hesitate to ask for any more questions, thank you for your help!

Edit: I will be modifying the other issues as well, just finding the time to do so.

**Comment by MostDeadDeveloper** [comment]
The Change could possibly include updating the current guidelines about git  that I made in the past, that is quite old,

**Comment by pratiksasmal** [comment]
Great, I will start working on it then. I am pretty new to writing documentation but will try my best. Thanks for letting me work on it.

**Comment by MostDeadDeveloper** [comment]
consider rechanging the  step 3 as well of the step by step guide, the step by step I made is only for repositories that a person have complete access to. Or you can enhance the step 3 further to make it more concise.

Other than that I think most of it is already good.

**Comment by pratiksasmal** [comment]
Ok. I will start working on it. Also do you want me to make any changes in the step 4 as well or is it fine.

**Comment by MostDeadDeveloper** [comment]
Sure! Thanks!
